version: '3.1'

services:
  db:
    image: postgres:14.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - ./db/volumes/postgresql/data/:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
